sudo: false
language: erlang
install: true
otp_release:
- 19.1
- 18.0
- 17.5
# - R16B03-1 # FIXME: namespaced_types
# - R15B03
before_script:
- wget https://s3.amazonaws.com/rebar3/rebar3
- chmod +x rebar3
env: PATH=.:$PATH
script: rebar3 ct && rebar3 coveralls send
cache:
  directories:
  - $HOME/.cache/rebar3
